spring.datasource.url=jdbc:postgresql://localhost:5432/ecoimpact_db
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.threads.virtual.enabled=true
app.cors.allowed-origins=http://localhost:5173
spring.thymeleaf.check-template-location=false 
spring.jpa.open-in-view=false